require('dotenv').config();
const express = require('express');
const cors = require('cors');
const multer = require('multer');
// ✅ FIX: Do NOT require pdf-parse at the top level — it crashes on startup.
//    It is required lazily inside the route handler only when a PDF is uploaded.
const { GoogleGenerativeAI } = require('@google/generative-ai');

const app = express();
const PORT = process.env.PORT || 5001; // ✅ Fixed: matches frontend (localhost:5001)



// Middleware
app.use(cors({
    origin: '*', // ✅ Allow all origins in dev. In production, set to your frontend URL.
    methods: ['GET', 'POST'],
}));
app.use(express.json());

const upload = multer({ storage: multer.memoryStorage() });

// ─────────────────────────────────────────
// Health Check  (only ONE definition now)
// ─────────────────────────────────────────
app.get('/api/health', (req, res) => {
    res.json({
        status: 'UP',
        message: 'StudySphere Backend is running!',
        timestamp: new Date().toISOString()
    });
});

// ─────────────────────────────────────────
// AI Study Roadmap Generator (Gemini)
// ─────────────────────────────────────────
app.post('/api/generate-plan', upload.single('document'), async (req, res) => {
    try {
        const { subject, days, hoursPerDay } = req.body;
        const file = req.file;

        let contextText = subject ? subject.trim() : 'General Computer Science Topics';

        // Extract text from uploaded PDF (if any)
        if (file) {
            try {
                // ✅ Lazy require — only loads pdf-parse when a PDF is actually uploaded
                const pdfParse = require('pdf-parse');
                const pdfData = await pdfParse(file.buffer);
                const extracted = pdfData.text.trim();
                if (extracted.length > 0) {
                    contextText = extracted.substring(0, 15000);
                }
            } catch (pdfErr) {
                console.warn('PDF parsing failed, falling back to subject text:', pdfErr.message);
            }
        }

        const totalDays  = parseInt(days)       || 30;
        const dailyHours = parseInt(hoursPerDay) || 2;
        const totalHours = totalDays * dailyHours;

        // ✅ API key must ONLY come from .env — never hardcode it in source
        const apiKey = process.env.GEMINI_API_KEY;

        if (apiKey) {
            // ── Gemini Path ──────────────────────────────────────────────
            const genAI = new GoogleGenerativeAI(apiKey);
            const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });

            const prompt = `
You are an expert academic planner.
Context to study: ${contextText}
The student has exactly ${totalDays} days to study, committing ${dailyHours} hours per day (Total: ${totalHours} hours).

Break down the fundamental and advanced concepts from the context into a sequential study roadmap.
Allocate specific hours to each concept so the sum of ALL hoursAllocated equals EXACTLY ${totalHours} hours.

Return ONLY a valid JSON array — no markdown, no explanation, no extra text.
Format:
[
  { "id": 1, "task": "Concept Name", "due": "Day X", "hoursAllocated": 4, "completed": false }
]
`;

            const result      = await model.generateContent(prompt);
            let responseText  = result.response.text().trim();

            // Strip any accidental markdown code-fence wrapping
            responseText = responseText.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim();

            // Extract the JSON array boundaries safely
            const startIndex = responseText.indexOf('[');
            const endIndex   = responseText.lastIndexOf(']');

            if (startIndex === -1 || endIndex === -1) {
                throw new Error('Gemini did not return a valid JSON array.');
            }

            responseText = responseText.substring(startIndex, endIndex + 1);
            const parsedTasks = JSON.parse(responseText);

            return res.json({
                success: true,
                tasks: parsedTasks,
                message: 'AI Roadmap Generated by Gemini!'
            });

        } else {
            // ── Mock Fallback (no API key) ────────────────────────────────
            console.warn('⚠️  No GEMINI_API_KEY in .env — returning mock roadmap.');

            const concepts = [
                'Fundamentals & Basics',
                'Core Algorithms',
                'Advanced Theory',
                'Practical Real-world Application',
                'Mock Testing Phase',
                'Final Comprehensive Review'
            ];

            let hoursLeft = totalHours;
            const hoursPerConcept = Math.floor(totalHours / concepts.length);

            const fakeTasks = concepts.map((concept, index) => {
                const isLast = index === concepts.length - 1;
                const hours  = isLast ? hoursLeft : hoursPerConcept;
                hoursLeft   -= hours;

                return {
                    id:             index + 1, // ✅ ids start at 1, never 0
                    task:           `${concept} — ${subject || 'Uploaded Material'}`,
                    due:            `Day ${Math.ceil((index + 1) * (totalDays / concepts.length))}`,
                    hoursAllocated: hours,
                    completed:      false
                };
            });

            return res.json({
                success: true,
                tasks:   fakeTasks,
                message: 'Mock roadmap returned. Add GEMINI_API_KEY to .env for real AI output.'
            });
        }

    } catch (err) {
        console.error('❌ Error generating plan:', err);
        res.status(500).json({
            success: false,
            // ✅ Send the real error so the frontend can display it
            message: err.message || 'Failed to generate AI plan.',
            error:   err.message
        });
    }
});

// ─────────────────────────────────────────
// Concept Deep-Dive (per card detail)
// ─────────────────────────────────────────
app.post('/api/concept-detail', async (req, res) => {
    try {
        const { task, subject, hoursAllocated, due } = req.body;

        if (!task) return res.status(400).json({ success: false, message: 'task is required.' });

        const apiKey = process.env.GEMINI_API_KEY;
        if (!apiKey) return res.status(500).json({ success: false, message: 'No GEMINI_API_KEY set.' });

        const genAI = new GoogleGenerativeAI(apiKey);
        const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });

        const prompt = `
You are an expert teacher and academic content writer.
Generate a comprehensive deep-dive study guide for the following concept:

Concept: "${task}"
${subject ? `Subject Area: ${subject}` : ''}
${hoursAllocated ? `Study Time Allocated: ${hoursAllocated} hours` : ''}
${due ? `Scheduled: ${due}` : ''}

Return ONLY a valid JSON object — no markdown fences, no extra text.
Use this exact format:
{
  "title": "Full concept title",
  "overview": "2-3 sentence high-level overview of the concept",
  "sections": [
    {
      "heading": "Section heading",
      "content": "Detailed explanation paragraph",
      "subsections": [
        { "subheading": "Subsection title", "content": "Detailed explanation" }
      ]
    }
  ],
  "definitions": [
    { "term": "Key term", "definition": "Clear definition" }
  ],
  "examples": [
    { "title": "Example title", "description": "Brief real-world example to illustrate the concept" }
  ],
  "solvedExamples": [
    {
      "problem": "A clearly stated problem to solve",
      "steps": [
        { "stepNumber": 1, "explanation": "What you do in this step and why" }
      ],
      "finalAnswer": "The complete answer or result",
      "takeaway": "What this example teaches about the concept"
    }
  ],
  "practiceQuestions": [
    { "question": "Sample question?", "hint": "Brief hint to approach it" }
  ],
  "relatedConcepts": [
    { "name": "Related concept name", "relevance": "Why it's related" }
  ],
  "proTip": "One expert tip for mastering this concept"
}
`;

        const result     = await model.generateContent(prompt);
        let responseText = result.response.text().trim();

        // Strip markdown fences if present
        responseText = responseText.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim();

        const startIndex = responseText.indexOf('{');
        const endIndex   = responseText.lastIndexOf('}');
        if (startIndex === -1 || endIndex === -1) throw new Error('Gemini did not return valid JSON.');

        const detail = JSON.parse(responseText.substring(startIndex, endIndex + 1));
        return res.json({ success: true, detail });

    } catch (err) {
        console.error('❌ Concept detail error:', err);
        res.status(500).json({ success: false, message: err.message || 'Failed to fetch concept detail.' });
    }
});

// ─────────────────────────────────────────
// Learning Hub
// ─────────────────────────────────────────
app.get('/api/learning-hub', (req, res) => {
    console.log('📚 Learning Hub API hit!');
    res.json({
        success: true,
        message: 'Backend API executed successfully! Connected to Node.js.',
        modules: [
            { id: 1, title: 'Introduction to React',   progress: '100%' },
            { id: 2, title: 'Advanced Express API',     progress: '45%'  },
            { id: 3, title: 'Database Optimization',    progress: '10%'  }
        ]
    });
});

// ─────────────────────────────────────────
// Study Planner  (initial cache load)
// ─────────────────────────────────────────
app.get('/api/study-planner', (req, res) => {
    console.log('📅 Study Planner API hit!');
    res.json({
        success: true,
        message: 'Study Planner data loaded from backend.',
        tasks: [
            { id: 1, task: 'Complete Calculus Chapter 4', due: 'Today'    },
            { id: 2, task: 'Review Physics Notes',         due: 'Tomorrow' },
            { id: 3, task: 'Write English Essay',          due: 'Friday'   }
        ]
    });
});

// ─────────────────────────────────────────
// AI Chat
// ─────────────────────────────────────────
app.get('/api/ai-chat', (req, res) => {
    console.log('🤖 AI Chat API hit!');
    res.json({
        success: true,
        message: 'AI Assistant backend connected and ready.',
        status:  'Online',
        recentQueries: ['Explain quantum entanglement', 'How does useState work?']
    });
});

// ─────────────────────────────────────────
// Analytics
// ─────────────────────────────────────────
app.get('/api/analytics', (req, res) => {
    console.log('📊 Analytics API hit!');
    res.json({
        success: true,
        message: 'Analytics data successfully fetched.',
        stats: {
            studyHours:   42,
            averageScore: '88%',
            topSubject:   'Computer Science'
        }
    });
});

// Add this to your existing server.js
app.post('/api/chat', async (req, res) => {
    try {
        const { message } = req.body;
        const apiKey = process.env.GEMINI_API_KEY;

        if (!apiKey) return res.status(500).json({ success: false, message: "API Key missing" });

        const genAI = new GoogleGenerativeAI(apiKey);
        // Ensure you use the correct model name
        const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

        const prompt = `You are the StudySphere AI Tutor. Be concise and helpful. 
        Student query: ${message}`;

        const result = await model.generateContent(prompt);
        const response = await result.response;
        const text = response.text().trim();

        // Send back a clean response
        res.json({ success: true, reply: text });
    } catch (err) {
        console.error("Chat Error:", err);
        // If Gemini hits a safety filter or quota, it throws here.
        res.status(500).json({ 
            success: false, 
            message: "AI Error: " + err.message 
        });
    }
});

// ─────────────────────────────────────────
// Start Server
// ─────────────────────────────────────────
app.listen(PORT, () => {
    console.log(`🚀 Server running at http://localhost:${PORT}`);
});